### ISSUE TITLE
Split navs based on type (mobile/web)

### ISSUE THREAD

**Issue by Mgayar-sci** [Muhamed-Sarhan/NasNav-Yeshtery#1]
https://github.com/Muhamed-Sarhan/NasNav-Yeshtery/blob/2fc2edf1ff1c5cbd77decf89c13ed03d75db3426/src/components/Navs/index.js#L13:L32

Why are the mob and web components added together? Why not added under one group and hidden/shown once?

```html
<div className="wrapper">
      <div className="nav-web">
        <FirstNav />
        <SecondNav />
        <ThirdNav />
      </div>
      <div className="nav-mobile">
        <FirstNavMobile/>
        <SecondNavMobile />
        <ThirdNavMobile />
      </div>     
    </div>
```

and https://github.com/Muhamed-Sarhan/NasNav-Yeshtery/blob/292528b0f34811458dbf01bc987df7b96990595b/src/components/Navs/navsStyle.scss should look like:

```scss
.nav-mobile{
  display: none;
}

@media screen and (max-width: 800px) {
  .nav-web{
    display: none;
  }
  .nav-mobile{
    display: block;
  }
}
```
